// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staging_src_k8s.io_apimachinery_pkg_apis_meta_v1beta1_generated.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "staging_src_k8s.io_apimachinery_pkg_apis_meta_v1_generated.pb.h"
#include "staging_src_k8s.io_apimachinery_pkg_runtime_schema_generated.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto;
namespace k8s {
namespace io {
namespace apimachinery {
namespace pkg {
namespace apis {
namespace meta {
namespace v1beta1 {
class PartialObjectMetadataList;
struct PartialObjectMetadataListDefaultTypeInternal;
extern PartialObjectMetadataListDefaultTypeInternal _PartialObjectMetadataList_default_instance_;
}  // namespace v1beta1
}  // namespace meta
}  // namespace apis
}  // namespace pkg
}  // namespace apimachinery
}  // namespace io
}  // namespace k8s
PROTOBUF_NAMESPACE_OPEN
template<> ::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList* Arena::CreateMaybeMessage<::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace k8s {
namespace io {
namespace apimachinery {
namespace pkg {
namespace apis {
namespace meta {
namespace v1beta1 {

// ===================================================================

class PartialObjectMetadataList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList) */ {
 public:
  inline PartialObjectMetadataList() : PartialObjectMetadataList(nullptr) {}
  ~PartialObjectMetadataList() override;
  explicit PROTOBUF_CONSTEXPR PartialObjectMetadataList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PartialObjectMetadataList(const PartialObjectMetadataList& from);
  PartialObjectMetadataList(PartialObjectMetadataList&& from) noexcept
    : PartialObjectMetadataList() {
    *this = ::std::move(from);
  }

  inline PartialObjectMetadataList& operator=(const PartialObjectMetadataList& from) {
    CopyFrom(from);
    return *this;
  }
  inline PartialObjectMetadataList& operator=(PartialObjectMetadataList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PartialObjectMetadataList& default_instance() {
    return *internal_default_instance();
  }
  static inline const PartialObjectMetadataList* internal_default_instance() {
    return reinterpret_cast<const PartialObjectMetadataList*>(
               &_PartialObjectMetadataList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PartialObjectMetadataList& a, PartialObjectMetadataList& b) {
    a.Swap(&b);
  }
  inline void Swap(PartialObjectMetadataList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PartialObjectMetadataList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PartialObjectMetadataList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PartialObjectMetadataList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PartialObjectMetadataList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PartialObjectMetadataList& from) {
    PartialObjectMetadataList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PartialObjectMetadataList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList";
  }
  protected:
  explicit PartialObjectMetadataList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 1,
    kMetadataFieldNumber = 2,
  };
  // repeated .k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata items = 1;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata >*
      mutable_items();
  private:
  const ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata& _internal_items(int index) const;
  ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata* _internal_add_items();
  public:
  const ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata& items(int index) const;
  ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata >&
      items() const;

  // optional .k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta metadata = 2;
  bool has_metadata() const;
  private:
  bool _internal_has_metadata() const;
  public:
  void clear_metadata();
  const ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta& metadata() const;
  PROTOBUF_NODISCARD ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* release_metadata();
  ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* mutable_metadata();
  void set_allocated_metadata(::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* metadata);
  private:
  const ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta& _internal_metadata() const;
  ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* _internal_mutable_metadata();
  public:
  void unsafe_arena_set_allocated_metadata(
      ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* metadata);
  ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* unsafe_arena_release_metadata();

  // @@protoc_insertion_point(class_scope:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata > items_;
    ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* metadata_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PartialObjectMetadataList

// optional .k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta metadata = 2;
inline bool PartialObjectMetadataList::_internal_has_metadata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.metadata_ != nullptr);
  return value;
}
inline bool PartialObjectMetadataList::has_metadata() const {
  return _internal_has_metadata();
}
inline const ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta& PartialObjectMetadataList::_internal_metadata() const {
  const ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* p = _impl_.metadata_;
  return p != nullptr ? *p : reinterpret_cast<const ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta&>(
      ::k8s::io::apimachinery::pkg::apis::meta::v1::_ListMeta_default_instance_);
}
inline const ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta& PartialObjectMetadataList::metadata() const {
  // @@protoc_insertion_point(field_get:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.metadata)
  return _internal_metadata();
}
inline void PartialObjectMetadataList::unsafe_arena_set_allocated_metadata(
    ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* metadata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.metadata_);
  }
  _impl_.metadata_ = metadata;
  if (metadata) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.metadata)
}
inline ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* PartialObjectMetadataList::release_metadata() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* PartialObjectMetadataList::unsafe_arena_release_metadata() {
  // @@protoc_insertion_point(field_release:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.metadata)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
  return temp;
}
inline ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* PartialObjectMetadataList::_internal_mutable_metadata() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.metadata_ == nullptr) {
    auto* p = CreateMaybeMessage<::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta>(GetArenaForAllocation());
    _impl_.metadata_ = p;
  }
  return _impl_.metadata_;
}
inline ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* PartialObjectMetadataList::mutable_metadata() {
  ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* _msg = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.metadata)
  return _msg;
}
inline void PartialObjectMetadataList::set_allocated_metadata(::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta* metadata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.metadata_);
  }
  if (metadata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(metadata));
    if (message_arena != submessage_arena) {
      metadata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, metadata, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.metadata_ = metadata;
  // @@protoc_insertion_point(field_set_allocated:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.metadata)
}

// repeated .k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata items = 1;
inline int PartialObjectMetadataList::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int PartialObjectMetadataList::items_size() const {
  return _internal_items_size();
}
inline ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata* PartialObjectMetadataList::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata >*
PartialObjectMetadataList::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.items)
  return &_impl_.items_;
}
inline const ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata& PartialObjectMetadataList::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata& PartialObjectMetadataList::items(int index) const {
  // @@protoc_insertion_point(field_get:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.items)
  return _internal_items(index);
}
inline ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata* PartialObjectMetadataList::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata* PartialObjectMetadataList::add_items() {
  ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::k8s::io::apimachinery::pkg::apis::meta::v1::PartialObjectMetadata >&
PartialObjectMetadataList::items() const {
  // @@protoc_insertion_point(field_list:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.items)
  return _impl_.items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1beta1
}  // namespace meta
}  // namespace apis
}  // namespace pkg
}  // namespace apimachinery
}  // namespace io
}  // namespace k8s

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto
