// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staging_src_k8s.io_apimachinery_pkg_api_resource_generated.proto

#include "staging_src_k8s.io_apimachinery_pkg_api_resource_generated.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace k8s {
namespace io {
namespace apimachinery {
namespace pkg {
namespace api {
namespace resource {
PROTOBUF_CONSTEXPR Quantity::Quantity(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.string_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct QuantityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuantityDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuantityDefaultTypeInternal() {}
  union {
    Quantity _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuantityDefaultTypeInternal _Quantity_default_instance_;
PROTOBUF_CONSTEXPR QuantityValue::QuantityValue(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.string_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct QuantityValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuantityValueDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuantityValueDefaultTypeInternal() {}
  union {
    QuantityValue _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuantityValueDefaultTypeInternal _QuantityValue_default_instance_;
}  // namespace resource
}  // namespace api
}  // namespace pkg
}  // namespace apimachinery
}  // namespace io
}  // namespace k8s
static ::_pb::Metadata file_level_metadata_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto = nullptr;

const uint32_t TableStruct_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::api::resource::Quantity, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::api::resource::Quantity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::api::resource::Quantity, _impl_.string_),
  0,
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::api::resource::QuantityValue, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::api::resource::QuantityValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::api::resource::QuantityValue, _impl_.string_),
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, -1, sizeof(::k8s::io::apimachinery::pkg::api::resource::Quantity)},
  { 8, 15, -1, sizeof(::k8s::io::apimachinery::pkg::api::resource::QuantityValue)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::k8s::io::apimachinery::pkg::api::resource::_Quantity_default_instance_._instance,
  &::k8s::io::apimachinery::pkg::api::resource::_QuantityValue_default_instance_._instance,
};

const char descriptor_table_protodef_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n@staging_src_k8s.io_apimachinery_pkg_ap"
  "i_resource_generated.proto\022$k8s.io.apima"
  "chinery.pkg.api.resource\"\032\n\010Quantity\022\016\n\006"
  "string\030\001 \001(\t\"\037\n\rQuantityValue\022\016\n\006string\030"
  "\001 \001(\tB&Z$k8s.io/apimachinery/pkg/api/res"
  "ource"
  ;
static ::_pbi::once_flag descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto = {
    false, false, 205, descriptor_table_protodef_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto,
    "staging_src_k8s.io_apimachinery_pkg_api_resource_generated.proto",
    &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto::offsets,
    file_level_metadata_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto, file_level_enum_descriptors_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto,
    file_level_service_descriptors_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto_getter() {
  return &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto(&descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto);
namespace k8s {
namespace io {
namespace apimachinery {
namespace pkg {
namespace api {
namespace resource {

// ===================================================================

class Quantity::_Internal {
 public:
  using HasBits = decltype(std::declval<Quantity>()._impl_._has_bits_);
  static void set_has_string(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

Quantity::Quantity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:k8s.io.apimachinery.pkg.api.resource.Quantity)
}
Quantity::Quantity(const Quantity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Quantity* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.string_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.string_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.string_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_string()) {
    _this->_impl_.string_.Set(from._internal_string(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:k8s.io.apimachinery.pkg.api.resource.Quantity)
}

inline void Quantity::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.string_){}
  };
  _impl_.string_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.string_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Quantity::~Quantity() {
  // @@protoc_insertion_point(destructor:k8s.io.apimachinery.pkg.api.resource.Quantity)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Quantity::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.string_.Destroy();
}

void Quantity::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Quantity::Clear() {
// @@protoc_insertion_point(message_clear_start:k8s.io.apimachinery.pkg.api.resource.Quantity)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.string_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Quantity::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string string = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_string();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "k8s.io.apimachinery.pkg.api.resource.Quantity.string");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Quantity::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:k8s.io.apimachinery.pkg.api.resource.Quantity)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string string = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_string().data(), static_cast<int>(this->_internal_string().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "k8s.io.apimachinery.pkg.api.resource.Quantity.string");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_string(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:k8s.io.apimachinery.pkg.api.resource.Quantity)
  return target;
}

size_t Quantity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:k8s.io.apimachinery.pkg.api.resource.Quantity)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string string = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_string());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Quantity::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Quantity::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Quantity::GetClassData() const { return &_class_data_; }


void Quantity::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Quantity*>(&to_msg);
  auto& from = static_cast<const Quantity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:k8s.io.apimachinery.pkg.api.resource.Quantity)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_string()) {
    _this->_internal_set_string(from._internal_string());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Quantity::CopyFrom(const Quantity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:k8s.io.apimachinery.pkg.api.resource.Quantity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Quantity::IsInitialized() const {
  return true;
}

void Quantity::InternalSwap(Quantity* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.string_, lhs_arena,
      &other->_impl_.string_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Quantity::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto_getter, &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto_once,
      file_level_metadata_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto[0]);
}

// ===================================================================

class QuantityValue::_Internal {
 public:
  using HasBits = decltype(std::declval<QuantityValue>()._impl_._has_bits_);
  static void set_has_string(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

QuantityValue::QuantityValue(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
}
QuantityValue::QuantityValue(const QuantityValue& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  QuantityValue* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.string_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.string_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.string_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_string()) {
    _this->_impl_.string_.Set(from._internal_string(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
}

inline void QuantityValue::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.string_){}
  };
  _impl_.string_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.string_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

QuantityValue::~QuantityValue() {
  // @@protoc_insertion_point(destructor:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void QuantityValue::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.string_.Destroy();
}

void QuantityValue::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void QuantityValue::Clear() {
// @@protoc_insertion_point(message_clear_start:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.string_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QuantityValue::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string string = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_string();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "k8s.io.apimachinery.pkg.api.resource.QuantityValue.string");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* QuantityValue::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string string = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_string().data(), static_cast<int>(this->_internal_string().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "k8s.io.apimachinery.pkg.api.resource.QuantityValue.string");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_string(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
  return target;
}

size_t QuantityValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string string = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_string());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData QuantityValue::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    QuantityValue::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*QuantityValue::GetClassData() const { return &_class_data_; }


void QuantityValue::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<QuantityValue*>(&to_msg);
  auto& from = static_cast<const QuantityValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_string()) {
    _this->_internal_set_string(from._internal_string());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void QuantityValue::CopyFrom(const QuantityValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:k8s.io.apimachinery.pkg.api.resource.QuantityValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QuantityValue::IsInitialized() const {
  return true;
}

void QuantityValue::InternalSwap(QuantityValue* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.string_, lhs_arena,
      &other->_impl_.string_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata QuantityValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto_getter, &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto_once,
      file_level_metadata_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapi_5fresource_5fgenerated_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace resource
}  // namespace api
}  // namespace pkg
}  // namespace apimachinery
}  // namespace io
}  // namespace k8s
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::k8s::io::apimachinery::pkg::api::resource::Quantity*
Arena::CreateMaybeMessage< ::k8s::io::apimachinery::pkg::api::resource::Quantity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::k8s::io::apimachinery::pkg::api::resource::Quantity >(arena);
}
template<> PROTOBUF_NOINLINE ::k8s::io::apimachinery::pkg::api::resource::QuantityValue*
Arena::CreateMaybeMessage< ::k8s::io::apimachinery::pkg::api::resource::QuantityValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::k8s::io::apimachinery::pkg::api::resource::QuantityValue >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
