// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staging_src_k8s.io_apimachinery_pkg_apis_meta_v1beta1_generated.proto

#include "staging_src_k8s.io_apimachinery_pkg_apis_meta_v1beta1_generated.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace k8s {
namespace io {
namespace apimachinery {
namespace pkg {
namespace apis {
namespace meta {
namespace v1beta1 {
PROTOBUF_CONSTEXPR PartialObjectMetadataList::PartialObjectMetadataList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.items_)*/{}
  , /*decltype(_impl_.metadata_)*/nullptr} {}
struct PartialObjectMetadataListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PartialObjectMetadataListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PartialObjectMetadataListDefaultTypeInternal() {}
  union {
    PartialObjectMetadataList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PartialObjectMetadataListDefaultTypeInternal _PartialObjectMetadataList_default_instance_;
}  // namespace v1beta1
}  // namespace meta
}  // namespace apis
}  // namespace pkg
}  // namespace apimachinery
}  // namespace io
}  // namespace k8s
static ::_pb::Metadata file_level_metadata_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto = nullptr;

const uint32_t TableStruct_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList, _impl_.metadata_),
  PROTOBUF_FIELD_OFFSET(::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList, _impl_.items_),
  0,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::k8s::io::apimachinery::pkg::apis::meta::v1beta1::_PartialObjectMetadataList_default_instance_._instance,
};

const char descriptor_table_protodef_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\nEstaging_src_k8s.io_apimachinery_pkg_ap"
  "is_meta_v1beta1_generated.proto\022)k8s.io."
  "apimachinery.pkg.apis.meta.v1beta1\032@stag"
  "ing_src_k8s.io_apimachinery_pkg_apis_met"
  "a_v1_generated.proto\032Bstaging_src_k8s.io"
  "_apimachinery_pkg_runtime_schema_generat"
  "ed.proto\"\251\001\n\031PartialObjectMetadataList\022@"
  "\n\010metadata\030\002 \001(\0132..k8s.io.apimachinery.p"
  "kg.apis.meta.v1.ListMeta\022J\n\005items\030\001 \003(\0132"
  ";.k8s.io.apimachinery.pkg.apis.meta.v1.P"
  "artialObjectMetadataB+Z)k8s.io/apimachin"
  "ery/pkg/apis/meta/v1beta1"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto_deps[2] = {
  &::descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1_5fgenerated_2eproto,
  &::descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fruntime_5fschema_5fgenerated_2eproto,
};
static ::_pbi::once_flag descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto = {
    false, false, 465, descriptor_table_protodef_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto,
    "staging_src_k8s.io_apimachinery_pkg_apis_meta_v1beta1_generated.proto",
    &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto_once, descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto_deps, 2, 1,
    schemas, file_default_instances, TableStruct_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto::offsets,
    file_level_metadata_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto, file_level_enum_descriptors_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto,
    file_level_service_descriptors_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto_getter() {
  return &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto(&descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto);
namespace k8s {
namespace io {
namespace apimachinery {
namespace pkg {
namespace apis {
namespace meta {
namespace v1beta1 {

// ===================================================================

class PartialObjectMetadataList::_Internal {
 public:
  using HasBits = decltype(std::declval<PartialObjectMetadataList>()._impl_._has_bits_);
  static const ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta& metadata(const PartialObjectMetadataList* msg);
  static void set_has_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta&
PartialObjectMetadataList::_Internal::metadata(const PartialObjectMetadataList* msg) {
  return *msg->_impl_.metadata_;
}
void PartialObjectMetadataList::clear_metadata() {
  if (_impl_.metadata_ != nullptr) _impl_.metadata_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void PartialObjectMetadataList::clear_items() {
  _impl_.items_.Clear();
}
PartialObjectMetadataList::PartialObjectMetadataList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
}
PartialObjectMetadataList::PartialObjectMetadataList(const PartialObjectMetadataList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PartialObjectMetadataList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.items_){from._impl_.items_}
    , decltype(_impl_.metadata_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_metadata()) {
    _this->_impl_.metadata_ = new ::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta(*from._impl_.metadata_);
  }
  // @@protoc_insertion_point(copy_constructor:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
}

inline void PartialObjectMetadataList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.items_){arena}
    , decltype(_impl_.metadata_){nullptr}
  };
}

PartialObjectMetadataList::~PartialObjectMetadataList() {
  // @@protoc_insertion_point(destructor:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PartialObjectMetadataList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.items_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.metadata_;
}

void PartialObjectMetadataList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PartialObjectMetadataList::Clear() {
// @@protoc_insertion_point(message_clear_start:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.metadata_ != nullptr);
    _impl_.metadata_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PartialObjectMetadataList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata items = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_items(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional .k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta metadata = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_metadata(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PartialObjectMetadataList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata items = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_items(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional .k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta metadata = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::metadata(this),
        _Internal::metadata(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
  return target;
}

size_t PartialObjectMetadataList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata items = 1;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->_impl_.items_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional .k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta metadata = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.metadata_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PartialObjectMetadataList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PartialObjectMetadataList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PartialObjectMetadataList::GetClassData() const { return &_class_data_; }


void PartialObjectMetadataList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PartialObjectMetadataList*>(&to_msg);
  auto& from = static_cast<const PartialObjectMetadataList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.items_.MergeFrom(from._impl_.items_);
  if (from._internal_has_metadata()) {
    _this->_internal_mutable_metadata()->::k8s::io::apimachinery::pkg::apis::meta::v1::ListMeta::MergeFrom(
        from._internal_metadata());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PartialObjectMetadataList::CopyFrom(const PartialObjectMetadataList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PartialObjectMetadataList::IsInitialized() const {
  return true;
}

void PartialObjectMetadataList::InternalSwap(PartialObjectMetadataList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
  swap(_impl_.metadata_, other->_impl_.metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PartialObjectMetadataList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto_getter, &descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto_once,
      file_level_metadata_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5fapis_5fmeta_5fv1beta1_5fgenerated_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1beta1
}  // namespace meta
}  // namespace apis
}  // namespace pkg
}  // namespace apimachinery
}  // namespace io
}  // namespace k8s
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList*
Arena::CreateMaybeMessage< ::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::k8s::io::apimachinery::pkg::apis::meta::v1beta1::PartialObjectMetadataList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
