// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staging_src_k8s.io_apimachinery_pkg_util_intstr_generated.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5futil_5fintstr_5fgenerated_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5futil_5fintstr_5fgenerated_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5futil_5fintstr_5fgenerated_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5futil_5fintstr_5fgenerated_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5futil_5fintstr_5fgenerated_2eproto;
namespace k8s {
namespace io {
namespace apimachinery {
namespace pkg {
namespace util {
namespace intstr {
class IntOrString;
struct IntOrStringDefaultTypeInternal;
extern IntOrStringDefaultTypeInternal _IntOrString_default_instance_;
}  // namespace intstr
}  // namespace util
}  // namespace pkg
}  // namespace apimachinery
}  // namespace io
}  // namespace k8s
PROTOBUF_NAMESPACE_OPEN
template<> ::k8s::io::apimachinery::pkg::util::intstr::IntOrString* Arena::CreateMaybeMessage<::k8s::io::apimachinery::pkg::util::intstr::IntOrString>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace k8s {
namespace io {
namespace apimachinery {
namespace pkg {
namespace util {
namespace intstr {

// ===================================================================

class IntOrString final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:k8s.io.apimachinery.pkg.util.intstr.IntOrString) */ {
 public:
  inline IntOrString() : IntOrString(nullptr) {}
  ~IntOrString() override;
  explicit PROTOBUF_CONSTEXPR IntOrString(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IntOrString(const IntOrString& from);
  IntOrString(IntOrString&& from) noexcept
    : IntOrString() {
    *this = ::std::move(from);
  }

  inline IntOrString& operator=(const IntOrString& from) {
    CopyFrom(from);
    return *this;
  }
  inline IntOrString& operator=(IntOrString&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IntOrString& default_instance() {
    return *internal_default_instance();
  }
  static inline const IntOrString* internal_default_instance() {
    return reinterpret_cast<const IntOrString*>(
               &_IntOrString_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IntOrString& a, IntOrString& b) {
    a.Swap(&b);
  }
  inline void Swap(IntOrString* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IntOrString* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IntOrString* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IntOrString>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IntOrString& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IntOrString& from) {
    IntOrString::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntOrString* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "k8s.io.apimachinery.pkg.util.intstr.IntOrString";
  }
  protected:
  explicit IntOrString(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStrValFieldNumber = 3,
    kTypeFieldNumber = 1,
    kIntValFieldNumber = 2,
  };
  // optional string strVal = 3;
  bool has_strval() const;
  private:
  bool _internal_has_strval() const;
  public:
  void clear_strval();
  const std::string& strval() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_strval(ArgT0&& arg0, ArgT... args);
  std::string* mutable_strval();
  PROTOBUF_NODISCARD std::string* release_strval();
  void set_allocated_strval(std::string* strval);
  private:
  const std::string& _internal_strval() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_strval(const std::string& value);
  std::string* _internal_mutable_strval();
  public:

  // optional int64 type = 1;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  int64_t type() const;
  void set_type(int64_t value);
  private:
  int64_t _internal_type() const;
  void _internal_set_type(int64_t value);
  public:

  // optional int32 intVal = 2;
  bool has_intval() const;
  private:
  bool _internal_has_intval() const;
  public:
  void clear_intval();
  int32_t intval() const;
  void set_intval(int32_t value);
  private:
  int32_t _internal_intval() const;
  void _internal_set_intval(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:k8s.io.apimachinery.pkg.util.intstr.IntOrString)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr strval_;
    int64_t type_;
    int32_t intval_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5futil_5fintstr_5fgenerated_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IntOrString

// optional int64 type = 1;
inline bool IntOrString::_internal_has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool IntOrString::has_type() const {
  return _internal_has_type();
}
inline void IntOrString::clear_type() {
  _impl_.type_ = int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int64_t IntOrString::_internal_type() const {
  return _impl_.type_;
}
inline int64_t IntOrString::type() const {
  // @@protoc_insertion_point(field_get:k8s.io.apimachinery.pkg.util.intstr.IntOrString.type)
  return _internal_type();
}
inline void IntOrString::_internal_set_type(int64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.type_ = value;
}
inline void IntOrString::set_type(int64_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:k8s.io.apimachinery.pkg.util.intstr.IntOrString.type)
}

// optional int32 intVal = 2;
inline bool IntOrString::_internal_has_intval() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool IntOrString::has_intval() const {
  return _internal_has_intval();
}
inline void IntOrString::clear_intval() {
  _impl_.intval_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline int32_t IntOrString::_internal_intval() const {
  return _impl_.intval_;
}
inline int32_t IntOrString::intval() const {
  // @@protoc_insertion_point(field_get:k8s.io.apimachinery.pkg.util.intstr.IntOrString.intVal)
  return _internal_intval();
}
inline void IntOrString::_internal_set_intval(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.intval_ = value;
}
inline void IntOrString::set_intval(int32_t value) {
  _internal_set_intval(value);
  // @@protoc_insertion_point(field_set:k8s.io.apimachinery.pkg.util.intstr.IntOrString.intVal)
}

// optional string strVal = 3;
inline bool IntOrString::_internal_has_strval() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool IntOrString::has_strval() const {
  return _internal_has_strval();
}
inline void IntOrString::clear_strval() {
  _impl_.strval_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& IntOrString::strval() const {
  // @@protoc_insertion_point(field_get:k8s.io.apimachinery.pkg.util.intstr.IntOrString.strVal)
  return _internal_strval();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IntOrString::set_strval(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.strval_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:k8s.io.apimachinery.pkg.util.intstr.IntOrString.strVal)
}
inline std::string* IntOrString::mutable_strval() {
  std::string* _s = _internal_mutable_strval();
  // @@protoc_insertion_point(field_mutable:k8s.io.apimachinery.pkg.util.intstr.IntOrString.strVal)
  return _s;
}
inline const std::string& IntOrString::_internal_strval() const {
  return _impl_.strval_.Get();
}
inline void IntOrString::_internal_set_strval(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.strval_.Set(value, GetArenaForAllocation());
}
inline std::string* IntOrString::_internal_mutable_strval() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.strval_.Mutable(GetArenaForAllocation());
}
inline std::string* IntOrString::release_strval() {
  // @@protoc_insertion_point(field_release:k8s.io.apimachinery.pkg.util.intstr.IntOrString.strVal)
  if (!_internal_has_strval()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.strval_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.strval_.IsDefault()) {
    _impl_.strval_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void IntOrString::set_allocated_strval(std::string* strval) {
  if (strval != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.strval_.SetAllocated(strval, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.strval_.IsDefault()) {
    _impl_.strval_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:k8s.io.apimachinery.pkg.util.intstr.IntOrString.strVal)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace intstr
}  // namespace util
}  // namespace pkg
}  // namespace apimachinery
}  // namespace io
}  // namespace k8s

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_staging_5fsrc_5fk8s_2eio_5fapimachinery_5fpkg_5futil_5fintstr_5fgenerated_2eproto
