// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test-struct.proto
// Protobuf C++ Version: 4.26.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_test_2dstruct_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_test_2dstruct_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 4026000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_test_2dstruct_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_test_2dstruct_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_test_2dstruct_2eproto;
namespace teststruct {
class testStruct;
struct testStructDefaultTypeInternal;
extern testStructDefaultTypeInternal _testStruct_default_instance_;
}  // namespace teststruct
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace teststruct {

// ===================================================================


// -------------------------------------------------------------------

class testStruct final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:teststruct.testStruct) */ {
 public:
  inline testStruct() : testStruct(nullptr) {}
  ~testStruct() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR testStruct(
      ::google::protobuf::internal::ConstantInitialized);

  inline testStruct(const testStruct& from) : testStruct(nullptr, from) {}
  inline testStruct(testStruct&& from) noexcept
      : testStruct(nullptr, std::move(from)) {}
  inline testStruct& operator=(const testStruct& from) {
    CopyFrom(from);
    return *this;
  }
  inline testStruct& operator=(testStruct&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const testStruct& default_instance() {
    return *internal_default_instance();
  }
  static inline const testStruct* internal_default_instance() {
    return reinterpret_cast<const testStruct*>(
        &_testStruct_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(testStruct& a, testStruct& b) { a.Swap(&b); }
  inline void Swap(testStruct* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(testStruct* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  testStruct* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<testStruct>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const testStruct& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const testStruct& from) { testStruct::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(testStruct* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "teststruct.testStruct"; }

 protected:
  explicit testStruct(::google::protobuf::Arena* arena);
  testStruct(::google::protobuf::Arena* arena, const testStruct& from);
  testStruct(::google::protobuf::Arena* arena, testStruct&& from) noexcept
      : testStruct(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCharValueFieldNumber = 2,
    kIntValueFieldNumber = 1,
    kFloatValueFieldNumber = 3,
  };
  // optional string CharValue = 2;
  bool has_charvalue() const;
  void clear_charvalue() ;
  const std::string& charvalue() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_charvalue(Arg_&& arg, Args_... args);
  std::string* mutable_charvalue();
  PROTOBUF_NODISCARD std::string* release_charvalue();
  void set_allocated_charvalue(std::string* value);

  private:
  const std::string& _internal_charvalue() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_charvalue(
      const std::string& value);
  std::string* _internal_mutable_charvalue();

  public:
  // optional int32 IntValue = 1;
  bool has_intvalue() const;
  void clear_intvalue() ;
  ::int32_t intvalue() const;
  void set_intvalue(::int32_t value);

  private:
  ::int32_t _internal_intvalue() const;
  void _internal_set_intvalue(::int32_t value);

  public:
  // optional float FloatValue = 3;
  bool has_floatvalue() const;
  void clear_floatvalue() ;
  float floatvalue() const;
  void set_floatvalue(float value);

  private:
  float _internal_floatvalue() const;
  void _internal_set_floatvalue(float value);

  public:
  // @@protoc_insertion_point(class_scope:teststruct.testStruct)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      39, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr charvalue_;
    ::int32_t intvalue_;
    float floatvalue_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2dstruct_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// testStruct

// optional int32 IntValue = 1;
inline bool testStruct::has_intvalue() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void testStruct::clear_intvalue() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.intvalue_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t testStruct::intvalue() const {
  // @@protoc_insertion_point(field_get:teststruct.testStruct.IntValue)
  return _internal_intvalue();
}
inline void testStruct::set_intvalue(::int32_t value) {
  _internal_set_intvalue(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:teststruct.testStruct.IntValue)
}
inline ::int32_t testStruct::_internal_intvalue() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.intvalue_;
}
inline void testStruct::_internal_set_intvalue(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.intvalue_ = value;
}

// optional string CharValue = 2;
inline bool testStruct::has_charvalue() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void testStruct::clear_charvalue() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.charvalue_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& testStruct::charvalue() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:teststruct.testStruct.CharValue)
  return _internal_charvalue();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void testStruct::set_charvalue(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.charvalue_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:teststruct.testStruct.CharValue)
}
inline std::string* testStruct::mutable_charvalue() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_charvalue();
  // @@protoc_insertion_point(field_mutable:teststruct.testStruct.CharValue)
  return _s;
}
inline const std::string& testStruct::_internal_charvalue() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.charvalue_.Get();
}
inline void testStruct::_internal_set_charvalue(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.charvalue_.Set(value, GetArena());
}
inline std::string* testStruct::_internal_mutable_charvalue() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.charvalue_.Mutable( GetArena());
}
inline std::string* testStruct::release_charvalue() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:teststruct.testStruct.CharValue)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.charvalue_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.charvalue_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void testStruct::set_allocated_charvalue(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.charvalue_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.charvalue_.IsDefault()) {
          _impl_.charvalue_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:teststruct.testStruct.CharValue)
}

// optional float FloatValue = 3;
inline bool testStruct::has_floatvalue() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void testStruct::clear_floatvalue() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.floatvalue_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float testStruct::floatvalue() const {
  // @@protoc_insertion_point(field_get:teststruct.testStruct.FloatValue)
  return _internal_floatvalue();
}
inline void testStruct::set_floatvalue(float value) {
  _internal_set_floatvalue(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:teststruct.testStruct.FloatValue)
}
inline float testStruct::_internal_floatvalue() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.floatvalue_;
}
inline void testStruct::_internal_set_floatvalue(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.floatvalue_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace teststruct


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_test_2dstruct_2eproto_2epb_2eh
